# background_blur = true
# background_opacity = 0.9

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window.class]
instance = "Alacritty"

[window.dimensions]
columns = 113
lines = 29

[terminal]
